export const ADD_RECIPE = "ADD_RECIPE";
export const SELECT_RECIPE = "SELECT_RECIPE";
export const TOGGLE_TITLE = "TOGGLE_TITLE";
export const TOGGLE_SERVINGS = "TOGGLE_SERVINGS";
export const UPDATE_TITLE = "UPDATE_TITLE";
export const EDIT_RECIPE = "EDIT_RECIPE";
